#!/usr/bin/env python3

import os

import lib.init  # isort:skip
from tasklib.task import Task  # isort:skip


task = Task.from_input()


if not task["project"] and os.environ["PROJECT_NAME"]:
    task["project"] = os.environ["PROJECT_NAME"]

print(task.export_data())

print("ran!", task.export_data())
