---
repos:
  - repo: local
    hooks:
      - id: gitleaks-test
        name: Detect hardcoded secrets
        description: Detect hardcoded secrets using Gitleaks
        # have to use "dir" instead of "git" since files get passed :shrug:
        entry: gitleaks dir --redact --verbose
        verbose: true
        language: system
  - repo: local
    hooks:
      - id: lint
        name: Lint
        description: Lint all the files
        entry: just lint
        verbose: true
        pass_filenames: false
        language: system
