#!/usr/bin/env bash

set -euo pipefail

git submodule update --init --recursive .
SHELL=sh ./submodules/dotbot/bin/dotbot -v --plugin-dir submodules/dotbot-brew --plugin-dir submodules/dotbot-pip -c default.yaml
