- defaults:
    link:
      create: true
      relink: true
    brewfile:
      stdin: true
      stderr: true
      stdout: true

- create:
  - ~/.config
  - ~/.cache
  - ~/.tmux/plugins

- clean:
  - '~'
  - ~/.config
  - ~/.timewarrior
  - ~/.zsh


- link:
    ~/.config/alacritty: etc/alacritty
    ~/.config/bugwarrior: etc/bugwarrior
    ~/.config/karabiner: etc/karabiner
    ~/.config/kitty: etc/kitty
    ~/.config/nvim: etc/nvim
    ~/.config/ranger: etc/ranger
    ~/.config/the-way: etc/the-way
    ~/.config/starship.toml: etc/starship.toml
    ~/.gitconfig: etc/git/gitconfig
    ~/.gitignore_global: etc/git/gitignore
    ~/.grc: etc/grc
    ~/.taskrc: etc/taskrc
    ~/.timewarrior/timewarrior.cfg: etc/timewarrior.cfg
    ~/.tmux.conf: etc/tmux.conf
    ~/.tmux/plugins/tpm: submodules/tpm
    ~/.vim: etc/vim
    ~/.vimrc: etc/vimrc
    ~/.vimrc: etc/vimrc
    ~/.zgen: submodules/zgen
    ~/.zsh/.zprezto: submodules/zprezto
    ~/.zsh: etc/zsh
    ~/.zshenv: etc/zshenv
    ~/app: app
    ~/bin: bin

- pipx:
    file: requirements-pipx.txt
    stdout: false
    stderr: true

# TODO: fix venv
- pip:
    file: requirements.txt
    user: true    # Like --user
    stdout: false # Print the execution stdout
    stderr: true  # Print the execution stderr

# - shell:
#   - /usr/bin/python3 -m venv venv
#   - venv/bin/pip install -r requirements.txt

- install-brew: true
- brewfile:
    -  Brewfile
