[settings]
experimental = true
legacy_version_file = true

[tools]
"cargo:garden-gui" = "latest"
"cargo:garden-tools" = "latest"
"cargo:git-repo-manager" = "latest"
"go:github.com/knqyf263/pet" = "latest"
"go:github.com/zendesk/statsd-logger/cmd/statsd-logger" = "latest"
# "cargo:atomic-cli" = "latest"
# "cargo:atomic-server" = "latest"
'cargo:when-cli' = "latest"
age = "latest"
bat = "latest"
colima = "latest"
github-cli = "latest"
go = "latest"
hk = "latest"
hurl = "latest"
just = "latest"
neovim = "latest"
node = "latest"
pkl = "latest"
pnpm = "10.4.0"
python = "latest"
redis = "7.4.1"
usage = "latest"
uv = "latest"
yazi = "latest"
fd = "latest"
direnv = "latest"
dust = "latest"
fzf = "latest"
delta = "latest"
"cargo:fastmod" = "latest"
glow = "latest"
k9s = "latest"
jq = "latest"
kubectl = "latest"
"go:github.com/ankitpokhrel/jira-cli/cmd/jira" = "latest"
mkcert = "latest"
lazygit = "latest"
"cargo:sd" = "latest"
shfmt = "latest"
ripgrep = "latest"
"cargo:pueue" = "latest"
gcloud = "latest"
zoxide = "latest"
starship = "latest"
tmux = "latest"
sops = "latest"
"npm:prettier" = "latest"
shellcheck = "latest"
yq = "latest"
cocogitto = "latest"
"cargo:choose" = "latest"
difftastic = "latest"
"cargo:xan" = "latest"
chezmoi = "latest"
gitleaks = "latest"
