---
colors: &colors
  rows:
    even: "lightblue"
    odd: "white"
wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [45, 72, 72, 72]
    rows: [6,16, 26]
  refreshInterval: 1
  mods:
    clocks:
      title: Time
      colors: *colors
      enabled: true
      locations:
        Bangkok: "Asia/Bangkok"
        Stockholm: "Europe/Stockholm"
        "New York": "America/New_York"
        "Los Angeles": "America/Los_Angeles"
      position:
        top: 0
        left: 0
        height: 1
        width: 1
      refreshInterval: 15
      sort: "chronological"

    feedreader:
      title: News
      enabled: true
      feeds:
        - https://feed.urras.co?limit=20
      feedLimit: 20
      position:
        top: 0
        left: 1
        width: 2
        height: 2
      updateInterval: 14400
    
    exchangerates:
      enabled: true
      focusable: false
      position:
        top: 2
        left: 0
        width: 1
        height: 1
      rates:
        SEK:
          - THB
        EUR:
          - SEK
          - THB
          - USD
        USD:
          - SEK
          - THB
          - EUR

    istats:
      args: ["all"]
      cmd: "istats"
      enabled: true
      focusable: false
      type: "cmdrunner"
      position:
        top: 4
        left: 0
        height: 2
        width: 1
      refreshInterval: 1

    bittrex:
      enabled: true
      colors:
        base:
          name: lightblue
          displayName: white
        market:
          name: red
          field: white
          value: green
      enabled: true
      position:
        top: 1
        left: 0
        height: 1
        width: 1
      refreshInterval: 5
      summary:
        EUR:
          displayName: Bitcoin
          market:
            - BTC

    resourceusage:
      cpuCombined: false
      enabled: true
      position:
        top: 3
        left: 0
        height: 1
        width: 1
      refreshInterval: 1
      showCPU: true
      showMem: true
      showSwp: true

    sweden_current:
      type: cmdrunner
      args: [sweden]
      cmd: "/Users/anton/.config/wtf/corona.sh"
      enabled: true
      focusable: false
      border: false
      position:
        top: 2
        left: 1
        height: 2
        width: 3
      refreshInterval: 600

    thailand_current:
      type: cmdrunner
      args: [thailand]
      cmd: "/Users/anton/.config/wtf/corona.sh"
      enabled: true
      focusable: false
      border: false
      position:
        top: 2
        left: 2
        height: 2
        width: 3
      refreshInterval: 600

    us_current:
      type: cmdrunner
      args: [usa]
      cmd: "/Users/anton/.config/wtf/corona.sh"
      enabled: true
      focusable: false
      border: false
      position:
        top: 2
        left: 3
        height: 2
        width: 3
      refreshInterval: 600

    # spotify:
    #   enabled: true
    #   colors:
    #     label: "green"
    #     text: "white"
    #   position:
    #     top: 5
    #     left: 0
    #     height: 1
    #     width: 1
    #   refreshInterval: 0
    
    prettyweather:
      enabled: true
      city: Bangkok
      position:
        top: 3
        left: 1
        height: 3
        width: 2
      refreshInterval: 300
      unit: "m"
      view: 2
      language: "en"


    # security:
    #   enabled: true
    #   position:
    #     top: 1
    #     left: 2
    #     height: 1
    #     width: 1
    #   refreshInterval: 3600
    #

    #
    # TODO: When rate limit iss off
    # ipinfo:
    #   colors: *colors
    #   enabled: true
    #   position:
    #     top: 6
    #     left: 0
    #     height: 1
    #     width: 2
    #   refreshInterval: 180
