[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node"]
legacy_version_file = true

[tools]
# these are required first as backends might depend on them
cargo = "latest"
go = "latest"
node = "latest"
rust = "latest"
uv = "latest"

# general
age = "latest"
bat = "latest"
"cargo:choose" = "latest"
"cargo:fastmod" = "latest"
"cargo:garden-tools" = "latest"
"cargo:nomino" = "latest"
"cargo:pueue" = "latest"
"cargo:sd" = "latest"
"cargo:taskwarrior-tui" = "latest"
"cargo:when-cli" = "latest"
"cargo:xan" = "latest"
chezmoi = "latest"
cocogitto = "latest"
colima = "latest"
difftastic = "latest"
direnv = "latest"
dust = "latest"
envsubst = "latest"
fd = "latest"
fzf = "latest"
gcloud = "latest"
github-cli = "latest"
glow = "latest"
"go:github.com/ankitpokhrel/jira-cli/cmd/jira" = "latest"
"go:github.com/gokcehan/lf" = "latest"
"go:github.com/knqyf263/pet" = "latest"
"go:github.com/zendesk/statsd-logger/cmd/statsd-logger" = "latest"
hk = "latest"
hurl = "latest"
jq = "latest"
just = "latest"
k9s = "latest"
kubectl = "latest"
lazygit = "latest"
lua = "latest"
mkcert = "latest"
neovim = "latest"
"npm:prettier" = "latest"
"npm:svgo" = "latest"
pandoc = "latest"
"pipx:copier" = { version = "latest", uvx_args = "--with copier-templates-extensions" }
"pipx:tmuxp" = "latest"
pnpm = "latest"
python = "3.11" # avoid third party software (e.g. beautysh) breaking
redis = "latest"
ripgrep = "latest"
ruff = "latest"
shellcheck = "latest"
shfmt = "latest"
sops = "latest"
starship = "latest"
stylua = "latest"
tmux = "latest"
tree-sitter = "latest"
usage = "latest"
yq = "latest"
zoxide = "latest"
